# This is a sample to deploy a milvus cluster with minimum cost of resources.
# It should be used for testing and development purposes only.
# Total resources required is about: 0.1 CPU, 100 MiB memory
# When deleted, all the data in the Milvus will be lost.

apiVersion: milvus.io/v1beta1
kind: Milvus
metadata:
  name: my-release
  labels:
    app: milvus
spec:
  config: 
    common:
      security:
        tlsMode: 1 # 0: disable, 1: enable only server side, 2: enable client side
    tls:
      serverPemPath: configs/cert/server.pem
      serverKeyPath: configs/cert/server.key
      caPemPath: configs/cert/ca.pem